### ISSUE TITLE
 in responsive mode content data is overlapping the navbar tab

### ISSUE THREAD

**Issue by 8-bit-souvik** [8-bit-souvik/Securit#6]
<img width="49%" src="https://user-images.githubusercontent.com/72222987/134559472-734d3cb9-77bb-49e5-b3db-8c6ccea75fd5.png" />)<img width="49%" src="https://user-images.githubusercontent.com/72222987/134559493-941d6326-3818-4d47-95b3-1102374cde32.png"  />

<br/>

### issue occurring while navbar tab is popped up. content data, which are rendering through HBS dynamically (attribute is position: absolute) are overlapping on tab

**Comment by Abirpal202049** [comment]
I want to solve this issue

**Comment by 8-bit-souvik** [comment]
Good luck 💖 @Abirpal202049

**Comment by 8-bit-souvik** [comment]
thanks for contributing! 🎉
